config/routes.rb
Rails.application.routes.draw do

  resources :volunteer_applications

  resources :space_rental_requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'user#show'
  devise_for :users
  resources :user
  get '/user/event_detail/:id', to: 'events#event_detail', as: 'event_detail'
  post '/user/event_detail/:id', to: 'events#event_volunteer', as: 'event_volunteer'
  post '/user/event/:id', to: 'events#event_unvolunteer', as: 'event_unvolunteer'
  get '/volunteer/', to: 'volunteer_applications#volunteer', as: 'user_new_volunteer'
  post '/volunteer/', to: 'volunteer_applications#newVolunteer', as: 'user_volunteer'
  get '/hours/', to: 'available_hours#edit', as: 'edit_available_hours'
  post '/hours/', to: 'available_hours#update', as: 'update_available_hours'
  post '/start_date/', to: 'user#start_date', as: 'start_date'

end

app/views/shared/_calendar.html.erb
<!-- app/views/shared/_calendar.html.erb -->
<head>
    <title>Minimum Setup</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/calendar.css">
</head>
<body>
    <h3>Calendar</h3>
    <div id="calendar">
    <%= form_tag('/start_date') do %>
      <span id="date-picker">
        <%= date_select 'calendar', 'date', :discard_day => true, :order => [:month, :year], default: @theDate.to_date %>
        <div><%= submit_tag 'Submit', :id => "submit" %></div>
      </span>
      
    <% end -%>

      <%= @date_display %>
      <%= month_calendar events: @events do |date, event, info| %>
        <%= date.day %>

        <% event.each do |events| %>
          <div>
            <%=link_to events.name[0..10], event_detail_path(event) %>
          </div>
        <% end %>
      <% end %>

    </div>

    <script type="text/javascript" src="js/vendor/jquery-1.9.1.js"></script>
    <script type="text/javascript" src="js/vendor/underscore-min.js"></script>
    <script type="text/javascript" src="js/calendar.js"></script>
    <script type="text/javascript">
        var calendar = $("#calendar").calendar(
            {
                tmpl_path: "/tmpls/",
                events_source: @events
            });
    </script>
</body>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">BHNC Portal</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <% if current_user.admin %>
         <li><%= link_to 'Admin Dashboard', rails_admin_path %></li>
        <% end %>
        <li><%= link_to 'Volunteer', (current_user.volunteer or current_user.admin) ? edit_available_hours_path : user_new_volunteer_path %></li>
        <li><%= link_to 'Space Rentals', space_rental_requests_path %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
            <li><a href="#"><%= link_to 'Edit Profile', edit_user_registration_path(current_user) %></a></li>
            <li><a href="#"><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></a></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_space_rentals_calendar.html.erb
<!-- app/views/shared/_space_rental_calendar.html.erb -->
<body>
    <h1>Spaces being rented out</h1>
    <ul class="nav nav-tabs">
        <% @space_rental_locations.each do |location| %>
            <li><a href="#<%= location.gsub ' ', '_' %>" data-toggle="tab"><%= location %></a></li>
        <% end %>
    </ul>
    <div id="tab-content" class="tab-content">
        <% @space_rental_locations.each do |location| %>
            <% active = @space_rental_locations[0] == location ? "active" : "" %>
            <div class="tab-pane <%= active %>" id="<%= location.gsub ' ', '_' %>">
                <div id="calendar" class="day-schedule">
                    <%= week_calendar events: @space_rental_requests[location] do |date, rentals, info| %>
                        <%= date.day %>

                        <% start = date.beginning_of_day.advance(:hours => 8) %>
                        <% ending = start.advance(:hours => 12) %>
                        <table>
                        <% while start < ending do %>
                            <tr>
                            <% highlite = SpaceRentalRequest.highlight?(rentals, start) ? "highlite" : "" %>
                                <td class="<%= highlite %>">
                                    <div class="day-hour">
                                        <%= start.strftime("%I:%M %p") %>
                                        <% rentals.each do |rental|%>
                                            <% if rental.display_name?(start) %>
                                                <a data-toggle="tooltip" title="<%= rental.description%>"><%= rental.first_and_last_initial %></a>
                                            <% end %>
                                        <% end %>
                                    </div>
                                </td>
                            </tr>

                            <% start += 0.5.hours %>
                        <% end %>
                        </table>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</body>

app/views/shared/_upcoming_events.html.haml
%h3 Upcoming Events
%table{:class => "table table-condensed table-hover"}
  %thead
    %th Name
    %th Date
    %th Time
  %tbody
    - @events.each do |event|
      %tr{:class => ("info" if current_user.events.include?(event))}
        %td= link_to event.name[0..15], event_detail_path(event)
        %td= event.date
        %td= event.time