config/routes.rb
Rails.application.routes.draw do

  resources :volunteer_applications

  resources :space_rental_requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'user#show'
  devise_for :users
  resources :user
  get '/user/event_detail/:id', to: 'events#event_detail', as: 'event_detail'
  post '/user/event_detail/:id', to: 'events#event_volunteer', as: 'event_volunteer'
  post '/user/event/:id', to: 'events#event_unvolunteer', as: 'event_unvolunteer'
  get '/volunteer/', to: 'volunteer_applications#volunteer', as: 'user_new_volunteer'
  post '/volunteer/', to: 'volunteer_applications#newVolunteer', as: 'user_volunteer'
  get '/hours/', to: 'available_hours#edit', as: 'edit_available_hours'
  post '/hours/', to: 'available_hours#update', as: 'update_available_hours'
  post '/start_date/', to: 'user#start_date', as: 'start_date'

end

app/models/event.rb
class Event < ActiveRecord::Base
  extend SimpleCalendar
  has_calendar

  has_and_belongs_to_many :users, join_table: 'users_events'
  validates :name, presence: true
  validates :location, presence: true
  validates :starts_at, presence: true
  validates :end, presence: true
  scope :upcoming, lambda { where("starts_at > ?", DateTime.now) }

  def date
    time = self.starts_at.to_formatted_s(:long_ordinal).split(" ")
    time[0] + " " + time[1] + " " + time[2]
  end

  def time
    time1 = self.starts_at.to_formatted_s(:long_ordinal).split(" ")
    time2 = self.end.to_formatted_s(:long_ordinal).split(" ")
    time1[3] + " - " + time2[3]
  end
end

#rails g scaffold name alekfn:string
#rails

app/controllers/events_controller.rb
# app/controllers/events_controller.rb
class EventsController < ApplicationController
  def event_detail
    @event = Event.find params[:id]
  end

  def event_volunteer
    @event = Event.find params[:id]
    current_user.events << @event
    current_user.save
    flash[:notice] = "Successfully registered for #{@event.name}!"
    redirect_to event_detail_path
  end

  def event_unvolunteer
    @event = Event.find params[:id]
    current_user.events.delete(@event)
    @event.users.delete(current_user)
    current_user.save
    @event.save
    flash[:notice] = "Successfully unregistered for #{@event.name}!"
    redirect_to event_detail_path
  end

end

app/views/events/event_detail.html.haml
-# in app/views/events/event_detail
%h2= @event.name

%h3 Date
%p#date= @event.date

%h3 Time
%p#time= @event.time

%h3 Location
%p#location= @event.location

%h3 Description

%p#descrption= @event.description

- if current_user.volunteer or current_user.admin
  - if not current_user.events.include?(@event)
    =button_to 'Register To Volunteer', event_volunteer_path
  - else
    =button_to 'Unregister from Volunteering', event_unvolunteer_path
- else
  =link_to "Volunteer Sign Up", user_new_volunteer_path

/=link_to 'Back to home page', root_path