config/routes.rb
Rails.application.routes.draw do

  resources :volunteer_applications

  resources :space_rental_requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'user#show'
  devise_for :users
  resources :user
  get '/user/event_detail/:id', to: 'events#event_detail', as: 'event_detail'
  post '/user/event_detail/:id', to: 'events#event_volunteer', as: 'event_volunteer'
  post '/user/event/:id', to: 'events#event_unvolunteer', as: 'event_unvolunteer'
  get '/volunteer/', to: 'volunteer_applications#volunteer', as: 'user_new_volunteer'
  post '/volunteer/', to: 'volunteer_applications#newVolunteer', as: 'user_volunteer'
  get '/hours/', to: 'available_hours#edit', as: 'edit_available_hours'
  post '/hours/', to: 'available_hours#update', as: 'update_available_hours'
  post '/start_date/', to: 'user#start_date', as: 'start_date'

end

app/models/space_rental_request.rb
class SpaceRentalRequest < ActiveRecord::Base
  extend SimpleCalendar
  after_update :send_confirmation_email
  after_destroy :send_rejection_email
  belongs_to :user
  validates_presence_of :location
  validates_presence_of :start
  validates_presence_of :end
  validate :start_time_must_be_earlier_than_end_time
  has_calendar

  # Update later once we get list of spaces to rent
  def self.allLocations
    return ['BHNC 515 Cortland St downstairs multipurpose room', 'BHNC 515 Cortland St upstairs conference room', 'ECC 4468 Mission Street']
  end

  def approved?
    self.approved
  end

  def has_conflict
    SpaceRentalRequest.where(:approved => true, :location => self.location).find_each do |request|
      if overlaps_with(request.start) || overlaps_with(request.end)
        self.errors.add(:base, "#{self.location} is reserved at that time")
        return true
      end
    end
    return false
  end

  def start_time_must_be_earlier_than_end_time
    if self.end < self.start
      self.errors.add(:base, 'Request start time is after end time.')
    end
  end

  def starts_at
    self.start
  end

  def display_name?(time)
    self.user != nil && self.start >= time && self.start < (time + 0.5.hours)
  end

  def self.highlight?(rentals, time)
    rentals.each do |rental|
      if rental.display_name?(time) || rental.overlaps_with(time + 1.second)
        return true
      end
    end
    return false
  end

  def first_and_last_initial
    "#{self.user.first_name} #{self.user.last_name.to_s[0]}"
  end

  def overlaps_with(time)
    return time >= self.start && time <= self.end
  end

  def display_time(time)
    return time.strftime('%m/%d/%Y %l:%M %p')
  end

  def send_confirmation_email
    if self.approved
      ConfirmationMailer.rental_approved(self.user).deliver
    end
  end

  def send_rejection_email
    ConfirmationMailer.rental_denied(self.user).deliver
  end
end

app/controllers/space_rental_requests_controller.rb
class SpaceRentalRequestsController < ApplicationController
  before_action :set_space_rental_request, only: [:show, :edit, :update, :destroy]

  # GET /space_rental_requests
  # GET /space_rental_requests.json
  def index
    @space_rental_requests = SpaceRentalRequest.where(:user => current_user)
  end

  # GET /space_rental_requests/1
  # GET /space_rental_requests/1.json
  def show
    if SpaceRentalRequest.find(params[:id]).user != current_user
      redirect_to space_rental_requests_path
    end
  end

  # GET /space_rental_requests/new
  def new
    @space_rental_request = SpaceRentalRequest.new
  end

  # GET /space_rental_requests/1/edit
  def edit
  end

  # POST /space_rental_requests
  # POST /space_rental_requests.json
  def create
    @space_rental_request = SpaceRentalRequest.new(space_rental_request_params)
    @space_rental_request.user = current_user
    respond_to do |format|
      if @space_rental_request.has_conflict || !@space_rental_request.save
        show_errors(format, :new)
      else
        show_success(format, :created, 'Space rental request was successfully submitted. An email will be sent to you if the request is approved.')
      end
    end
  end

  # PATCH/PUT /space_rental_requests/1
  # PATCH/PUT /space_rental_requests/1.json
  def update
    respond_to do |format|
      if @space_rental_request.update(space_rental_request_params)
        show_success(format, :ok, 'Space rental request was successfully updated.')
      else
        show_errors(format, :edit)
      end
    end
  end

  # DELETE /space_rental_requests/1
  # DELETE /space_rental_requests/1.json
  def destroy
    @space_rental_request.destroy
    respond_to do |format|
      format.html { redirect_to space_rental_requests_url, notice: 'Space rental request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space_rental_request
      @space_rental_request = SpaceRentalRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_rental_request_params
      params.require(:space_rental_request).permit(:location, :start, :end, :description)
    end
    
    def show_success(format, status_message, notice_message)
        format.html { redirect_to @space_rental_request, notice: notice_message }
        format.json { render :show, status: status_message, location: @space_rental_request }
    end
    
    def show_errors(format, page)
        format.html { render page }
        format.json { render json: @space_rental_request.errors, status: :unprocessable_entity }
    end
end

app/helpers/space_rental_requests_helper.rb
module SpaceRentalRequestsHelper
end

app/views/space_rental_requests/_form.html.erb
<%= form_for(@space_rental_request) do |f| %>
  <% if @space_rental_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space_rental_request.errors.count, "error") %> prohibited this space_rental_request from being saved:</h2>

      <ul>
      <% @space_rental_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.select :location, SpaceRentalRequest.allLocations %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start, :start_hour => 8, :end_hour => 20, :ampm => true %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end, :start_hour => 8, :end_hour => 20, :ampm => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <h3>Hourly Rates</h3>
  BHNC downstairs multipurpose room or ECC
  <ul>
    <li> Private event: $80 </li>
    <li> Nonprofit/Bernal Heights/Excelsior neighborhood group: $65 </li>
    <li> BHNC member rate (group or individual): $65 </li>
  </ul>
  BHNC conference room
  <ul>
    <li> Private event: $65 </li>
    <li> Nonprofit/Bernal Heights/Excelsior neighborhood group: $50 </li>
    <li> BHNC member rate (group or individual): $50 </li>
  </ul>

  Above rates INCLUDE $25 per hour front-desk clerk for rentals outside of regular business
  hours.
  <br>
  $200 deposit required for all events; refundable subject to terms and limitations listed below.
  <br>
  Special rates may be available for daily, weekly, or monthly use.

  <h3>By submitting this request, you are agreeing to the following terms and limitations:</h3>
  <h5>USAGE OF Bernal Heights Neighborhood Center (BHNC) spaces, including BHNC's
  Excelsior Community Center (ECC):</h5>
  <ul>
    <li> Use of alcohol or illegal drugs is not permitted. </li>
    <li> Smoking in NOT ALLOWED at BHNC at ANY TIME. Smoking is prohibited by San
      Francisco’s Health Code: Ordinance 300-88. </li>
    <li> Helium-filled balloons NOT allowed. Balloons left behind will cause deposit to be retained. </li>
    <li> The piano is not to be moved for any reason. </li>
    <li> Use of kitchen limited to sink. Use of stove and refrigerator is NOT permitted. </li>
    <li> Unless authorized by the Executive Director, all events must end by 8:00 pm. </li>
  </ul>
  <h5>UPON COMPLETION OF YOUR USAGE:</h5>
  <ul>
    <li>Tables, floors, chairs and equipment must be left clean and returned to their original
      location. </li>
    <li> All decorations and signs must be taken down and all tape and pins removed from walls,
      etc. </li>
    <li> All windows must be fully closed and securely bolted. Turn off ceiling fans and/or heat. </li>
    <li> All lights at BHNC including the bathrooms (except for lobby lights) must be turned off. </li>
    <li> All trash should be neatly bagged and placed in black bin in the patio area. Recyclable and
      compostable materials should be properly sorted and placed in appropriate bins (blue for 
      recycling and green for composting) </li>
    <li> Ending time indicated in the contract is the time when you and your group will leave BHNC. </li>
    <li> Deposit will be held if needed to pay for lack of compliance with terms and limitations or for
      any damage to the property. </li>
  </ul>
  <h5>False Alarms:</h5>
  <ul>
    <li> A $150 resetting fee plus any expenses BHNC may incur due to a false alarm will be deducted from your deposit for setting off false alarms or abusing the fire safety equipment 
      (fire extinguishers, fire hoses, etc.)
  </ul>
  <h5>Emergency Contact Number:</h5>
  <ul>
    <li> 415 509-8269 or 415 254-9422 </li>
    <li> Please use only for emergencies. </li>
  </ul>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/space_rental_requests/edit.html.erb
<h1>Editing Space Rental Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @space_rental_request %> |
<%= link_to 'All requests', space_rental_requests_path %>

app/views/space_rental_requests/index.html.erb
<h1>Listing Your Space Rental Requests</h1>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Location</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @space_rental_requests.each do |space_rental_request| %>
      <tr>
        <td><%= space_rental_request.location %></td>
        <td><%= space_rental_request.display_time(space_rental_request.start) %></td>
        <td><%= space_rental_request.display_time(space_rental_request.end) %></td>
        <td><%= link_to 'Show Details', space_rental_request %></td>
        <td><%= link_to 'Edit Rental Request', edit_space_rental_request_path(space_rental_request) %></td>
        <td><%= link_to 'Delete Rental Request', space_rental_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space rental request', new_space_rental_request_path %>

app/views/space_rental_requests/new.html.erb
<h1>New Space Rental Request</h1>

<%= render 'form' %>

<%= link_to 'All requests', space_rental_requests_path %>

app/views/space_rental_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @space_rental_request.location %>
</p>

<p>
  <strong>Start:</strong>
  <%= @space_rental_request.display_time(@space_rental_request.start) %>
</p>

<p>
  <strong>End:</strong>
  <%= @space_rental_request.display_time(@space_rental_request.end) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @space_rental_request.description %>
</p>

<%= link_to 'Edit', edit_space_rental_request_path(@space_rental_request) %> |
<%= link_to 'Back', space_rental_requests_path %>